version: '2'

services:
  app:
    ports:
      - "8080:8080"
    image: 'auck:latest'
    build: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/auckland
      - SPRING_DATASOURCE_USERNAME=student
      - SPRING_DATASOURCE_PASSWORD=12121212
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=12121212
      - POSTGRES_DB=auckland