spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auckland
    username: student
    password: 12121212
  jpa:
    generate-ddl: true
    open-in-view: true
  mail:
    host: smtp.yandex.ru
    port: 465
    username: aucklandteam@yandex.ru
    password:
    properties:
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
      "mail.smtp.ssl.": smtp.yandex.ru
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 5000
      "mail.smtp.writetimeout": 5000
    default-encoding: UTF-8
    protocol: smtps

Auckland:
  app:
    jwtSecret: donttry
    jwtExpirationMs: 86400000
  mail:
    senderName: Auckland team
